create table public.organizations (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 150),
  join_code text not null unique check (char_length(join_code) = 8),
  created_by bigint,
  created_at timestamptz not null default now()
);

create table public.users (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 100),
  email text not null unique check (email = lower(email)),
  password text not null,
  account_type text not null default 'INDIVIDUAL'
    check (account_type in ('INDIVIDUAL', 'ORG_ADMIN', 'ORG_MEMBER')),
  organization_id bigint references public.organizations(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.organizations
  add constraint organizations_created_by_fkey
  foreign key (created_by) references public.users(id) on delete set null;

create table public.tasks (
  id bigint generated by default as identity primary key,
  owner_id bigint not null references public.users(id) on delete cascade,
  assigned_to bigint references public.users(id) on delete set null,
  organization_id bigint references public.organizations(id) on delete set null,
  title text not null check (char_length(title) between 1 and 200),
  description text not null default '',
  task_type text not null check (task_type in ('CURRICULAR', 'EXTRACURRICULAR', 'ORG')),
  due_date date not null,
  due_time time,
  priority text not null default 'MEDIUM' check (priority in ('LOW', 'MEDIUM', 'HIGH')),
  status text not null default 'PENDING' check (status in ('PENDING', 'IN_PROGRESS', 'COMPLETED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index tasks_owner_id_idx on public.tasks(owner_id);
create index tasks_assigned_to_idx on public.tasks(assigned_to);
create index tasks_organization_id_idx on public.tasks(organization_id);

alter table public.organizations enable row level security;
alter table public.users enable row level security;
alter table public.tasks enable row level security;
